module: FitDataProtocol 
author: Kevin A. Hoogheem
github_url: https://github.com/FitnessKit/FitDataProtocol

readme: README.md

output: docs
clean: true
theme: jony

copyright: '© 2017 Kevin A. Hoogheem'

xcodebuild_arguments: [-scheme,FitDataProtocol-Package]

custom_categories:
  - name: Decoder
    children:
    - FitFileDecoder
  
  - name: Encoder
    children:
    - FitFileEncoder
 
  - name: FIT Merge
    children:
    - FitFileMerger

  - name: FIT Messages
    children:
    - FitMessage
    - ActivityMessage
    - BloodPressureMessage
    - CadenceZoneMessage
    - ConnectivityMessage
    - CourseMessage
    - CoursePointMessage
    - DeveloperDataIdMessage
    - DeviceInfoMessage
    - EventMessage
    - ExerciseTitleMessage
    - FileCapabilitiesMessage
    - FileCreatorMessage
    - FileIdMessage
    - GoalMessage
    - HeartrateProfileMessage
    - HeartRateZoneMessage
    - HrvMessage
    - LapMessage
    - MetZoneMessage
    - PowerZoneMessage
    - RecordMessage
    - ScheduleMessage
    - SessionMessage
    - SlaveDeviceMessage
    - SoftwareMessage
    - SegmentLeaderboardEntryMessage
    - SpeedZoneMessage
    - SportMessage
    - StrideSpeedDistanceMonitorProfileMessage
    - TotalsMessage
    - UserProfileMessage
    - WeatherAlertMessage
    - WeightScaleMessage
    - WorkoutMessage
    - WorkoutSessionMessage
    - WorkoutStepMessage
    - ZonesTargetMessage

  - name: ExerciseName
    children:
    - ExerciseNameType
    - ExerciseNameSupportable
    - BenchPressExerciseName
    - CalfRaiseExerciseName
    - CardioExerciseName
    - CarryExerciseName
    - ChopExerciseName
    - CoreExerciseName
    - CrunchExerciseName
    - CurlExerciseName
    - DeadliftExerciseName
    - FlyeExerciseName
    - HipRaiseExerciseName
    - HipStabilityExerciseName
    - HipSwingExerciseName
    - HyperextensionExerciseName
    - LateralRaiseExerciseName
    - LegCurlExerciseName
    - OlympicLiftExerciseName
    - RunExerciseName
    - WarmUpExerciseName
