module: FitDataProtocol 
author: Kevin A. Hoogheem
github_url: https://github.com/FitnessKit/FitDataProtocol

readme: README.md

output: docs
clean: true

copyright: '© 2017 Kevin A. Hoogheem'

xcodebuild_arguments: [-scheme,FitDataProtocol-Package]

custom_categories:
  - name: Decoder
    children:
    - FitFileDecoder
 
  - name: FIT Merge
    children:
    - FitFileMerger

  - name: FIT Messages
    children:
    - FitMessage
    - ActivityMessage
    - CourseMessage
    - DeveloperDataIdMessage
    - DeviceInfoMessage
    - EventMessage
    - ExerciseTitleMessage
    - FileCreatorMessage
    - FileIdMessage
    - HeartRateZoneMessage
    - HrvMessage
    - RecordMessage
    - SportMessage
    - UserProfileMessage
    - WorkoutMessage
    - WorkoutStepMessage
